- src/Routes/Route.jsx
> Route updated by sourabh

- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
> added cards in travel page

- index.html
- src/Pages/Error/Error.jsx
- src/Routes/Route.jsx
error page updated and website title changed
> error page has been created by sourabh

- src/Pages/Events/Events.jsx
- src/Pages/Events/EventsComponents/EventBanner.jsx
> Event page banner created and added

- src/Pages/Authentication/LoginPage.jsx
- src/Pages/Authentication/RegisterPage.jsx
Added 2 Pages login and Registration right now there is no code
> Added 2 Pages login and Registration

- index.html
- src/Pages/Events/Events.jsx
- src/Pages/Events/EventsComponents/EventBanner.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
Hello I have created Event cards Please check and merge the code thank you .
> added event cards

- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
- src/Shared/Navbar/Navbar.jsx
added Your Ultimate Travel Companion section and select place section
> added Your Ultimate Travel Companion section and select place section

- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
added colour in bus set section
> added colour in bus set section

- package-lock.json
- package.json
- src/Hooks/useAxiosPublic.jsx
- src/Hooks/useAxiosSecure.jsx
added axios and create hook axiospublic and axiosSecure
> added axios and create hook axiospublic and axiosSecure

- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
fixed event card colors and design
> fixed event card colors and design

- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
> added select bus name

- src/Hooks/useEventPublic.jsx
- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
WORKING ON DETAILS PAGE DESIGN
> fixing details page

- src/Pages/Travel/AddTravelService/AddTravelService.jsx
- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
added a add your travel service section
> added a add your travel service section

- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
create scroll system in book now button
> create scroll system in book now button

- src/Pages/Entertainment/Components/FeaturedMovies.jsx
- src/Pages/Entertainment/Components/MovieGenres.jsx
- src/Pages/Entertainment/Components/MovieMarquee.jsx
- src/Pages/Entertainment/Entertainment.jsx
> normal text

- src/Pages/Travel/TravelComponents/TravelBanner.jsx
- src/Pages/Travel/TravelServiceSeciton/TravelService.jsx
- src/Shared/Footer/Footer.jsx
change some design and make responsive page
> change some design and make responsive page

- src/Pages/Travel/TravelServiceSeciton/BusReservationPage.jsx
- src/Pages/Travel/TravelServiceSeciton/TravelService.jsx
- src/Pages/Travel/TravelServiceSeciton/TravelServiceCard.jsx
- src/Routes/Route.jsx
> added bus reservation page

- src/Hooks/TrevalHook/useTravelData.jsx
- src/Pages/Travel/TravelServiceSeciton/TravelService.jsx
create a hook for data management  and store reservation data
> create a hook for data management  and store reservation data

- src/Hooks/TrevalHook/useTravelData.jsx
- src/Pages/Travel/TravelServiceSeciton/BusReservationPage.jsx
- src/components/Heading.jsx
polish the bus Reservation page
> polish the bus Reservation page

- src/Pages/Home/Home.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
- src/Pages/Travel/TravelTicekBook/useBusStandName.jsx
added bus stand name list change select place components
> added bus stand name list chang select place components

- src/Pages/Events/EventDetails/EventDetails.jsx
I added Timer on the details page
> added timer on the details page

- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/Events.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
Hello I Implemented dark mode on event section
> fully implemented dark mode on event section

- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
- src/Routes/Route.jsx
added travel bus ticeket page and fixed some bugs
> added travel bus ticeket page and fixed some bugs

- src/Pages/Events/EventsComponents/EventCards.jsx
Hello I added pagination on event Card section and changed Event card UI
> added pagination and redefined the card UI

- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
> Desgin bus ticek Card

- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
- src/Routes/Route.jsx
- src/components/BusTicketCancellation.jsx
added bus ticket cancellation policy and fixed some bugs
> added bus ticket cancellation policy and fixed some bugs

- src/Pages/Events/AllEvents/AllEvents.jsx
- src/Pages/MyWishList/MyWishList.jsx
- src/Routes/Route.jsx
- src/Shared/Navbar/Navbar.jsx
hello I created my wish list for future work i need a lot of works
> Creating WishList

- src/Hooks/TrevalHook/useTravelContext.jsx
- src/Provider/TravelProvider.jsx
- src/main.jsx
added context api for travel state management
> added context api for travel state mangement

- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelHooks/useBusState.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
- src/Provider/TravelProvider.jsx
fixed some bugs on search section send data from travel provider
> fixed some bugs on search section send data from travel provider

- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
- src/Pages/Travel/TravelHooks/useBusStandName.jsx
- src/Pages/Travel/TravelHooks/useBusState.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
added filter section in bus search page
> added filter section in bus search page

- package-lock.json
- package.json
- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelHooks/useBusStandName.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
- src/Provider/TravelProvider.jsx
- src/Routes/Route.jsx
fixed some bugs and make card dynamic
> fixed some bugs and make card daynamic

- src/Pages/Travel/FlashDeals/FlashDealCard.jsx
- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/components/Heading.jsx
work on dark light mode in travel page
> work on dark light mode in travel page

- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
- src/Pages/Events/EventsComponents/EventInfo.jsx
tryin to fix wishlist there has been made some changes still not fixed yet
> fixing wish list

- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelComponents/useCardData.jsx
change banner card content and make design better
> change banner card content and make design better

- src/Hooks/TrevalHook/useTravelData.jsx
- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelFAQ/TravelFAQ.jsx
- src/Pages/Travel/TravelServiceSeciton/BusReservationPage.jsx
- src/Pages/Travel/TravelServiceSeciton/TravelService.jsx
added FAQ section in travel page and also make it responsive and day night mode colour correction
> added FAQ section in travel page and also make it responsive and day night mode color correction

- src/Pages/Events/EventsComponents/EventCards.jsx
Hello i fixed event cards which wasnt fetching from new backend side
> Fixed Event Card 

- src/Pages/Events/AllEvents/AllEvents.jsx
- src/Pages/Events/EventDetails/EventDetails.jsx
fixed event details fetching problem
> fixed event details fetching problem

- src/Pages/Events/EventDetails/EventDetails.jsx
hi I added added new more suggestions on event section
> added new more suggestions on event section

- src/Pages/Dashboard/Events/ManageEventReviews/ManageEventReview.jsx
- src/Pages/Events/AllEvents/AllEvents.jsx
- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
- src/Routes/Route.jsx
Hello , I added comment button and modal
> added comment button and modal

- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
- src/Pages/Travel/TravelTicekBook/TravelUltimateCompanion.jsx
create travel ultimate companion and fixed some design
> create travel ultimate companion and fixed some design

- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
- src/Pages/Travel/TravelComponents/useCardData.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Pages/Travel/TravelTicekBook/TravelUltimateCompanion.jsx
> update user experiences

- src/Pages/Events/AllEvents/AllEvents.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
Hello I fixed event cards verified status filter
> fixed event cards verified status filter

- src/Pages/Dashboard/Entertainment/AddCineplex/AddCineplex.jsx
- src/Pages/Dashboard/Entertainment/AddMovie/AddMovie.jsx
- src/Pages/Dashboard/Entertainment/MovieManager/MovieDetails/MovieDetails.jsx
- src/Pages/Dashboard/Entertainment/MovieManager/MovieManager.jsx
- src/Routes/Route.jsx
> add the movie manage page and also the details page

- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
added address input in travel section
> added address input in travel section 

- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
design select place and time section
> design select palce and time section

- src/Pages/Travel/TravelServiceSeciton/BusReservationPage.jsx
> added alert in service page

- src/Layout/dashboard.jsx
- src/Pages/Dashboard/Travel/MyBusServices/BusDetailsModal/BusDetailsModal.jsx
- src/Pages/Dashboard/Travel/MyBusServices/MyBusServices.jsx
- src/Routes/Route.jsx
My Added Bus Services Page Design Done
> My Added Bus Services Page Design Done

- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
> fixed comment position 

- src/Layout/dashboard.jsx
- src/Pages/About/About.jsx
- src/Pages/Contact/Contact.jsx
- src/Shared/Navbar/Navbar.jsx
About, Contact and Navbar design edited. Redesign the about page and contact page. And Edit navbar color.
> About, Contact and Navbar design edited

- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelComponents/TravelTestimonials.jsx
- src/Pages/Travel/TravelComponents/WhyChooseUsTravel.jsx
> added Travel Testimonials

- src/Pages/Travel/TravelComponents/TravelTestimonials.jsx
solve responsive related problem and dark light mode
> solve responsive related problem and dark light mode 

- src/Pages/Events/AllEvents/AllEvents.jsx
- src/Pages/Events/Events.jsx
- src/Pages/Events/EventsComponents/EventCards.jsx
- src/Pages/Events/EventsComponents/EventInfo.jsx
> adding new events

- src/Pages/Events/AllEvents/AllEvents.jsx
> fixed cards grid view

- src/Hooks/useEventReview.jsx
- src/Pages/Dashboard/Events/ManageEventReviews/ManageEventReview.jsx
Hello, creating manage Review Section
> creating manage Review Section

- src/Pages/Dashboard/Travel/AddBusService/AddBusService.jsx
Bus can be added to database now
> Bus added to database

- src/Hooks/useEventReview.jsx
- src/Pages/Dashboard/Events/ManageEventReviews/ManageEventReview.jsx
- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Routes/Route.jsx
> added manage reviews

- src/Pages/Travel/AddTravelService/AddTravelService.jsx
- src/Pages/Travel/Travel.jsx
- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelComponents/WhyChooseUsTravel.jsx
> change design in travel page

- src/Pages/Events/EventDetails/EventDetails.jsx
> fixed comment section

- src/Pages/Travel/FlashDeals/FlashDeals.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
change design on time and place select section
>  change design on time and place select section

- src/Pages/Travel/AddTravelService/AddTravelService.jsx
- src/Pages/Travel/FlashDeals/FlashDeals.jsx
- src/Pages/Travel/TravelComponents/BannerCard.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
change some design in travel page
> change some design in travel page

- src/Pages/Travel/FlashDeals/FlashDealCard.jsx
- src/Pages/Travel/FlashDeals/FlashDeals.jsx
- src/Pages/Travel/TravelComponents/TravelBanner.jsx
- src/Pages/Travel/TravelPaymentReceipt/TravelPaymentSuccess.jsx
- src/Pages/Travel/TravelTicekBook/SelectPlaceTime.jsx
- src/Provider/TravelProvider.jsx
- src/Routes/Route.jsx
change card design for flash deal, polish design in banner section and place time select section for travel page
> change card design for flash deal, polish design in banner section and place time select section for travel page

- src/Pages/Dashboard/Events/ManageEventReviews/ManageEventReview.jsx
working on manage review section STILL NEEDS TO WORK
> working on manage review section

- src/Pages/Travel/BusCompaniesSection/BusCompaniesSection.jsx
- src/Pages/Travel/FlashDeals/FlashDeals.jsx
> fetch data for flash deals

- src/Pages/Travel/BusCompaniesSection/PopularBusRoutes.jsx
- src/Pages/Travel/Travel.jsx
> added Popular bus Routes

- src/Pages/Travel/BusCompaniesSection/PopularBusRoutes.jsx
added functionality for popular routs
> added functionality for popular routs

- src/Pages/Travel/TravelTicekBook/BusFilter.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
> added filter section

- src/Pages/Travel/TravelComponents/BusCard.jsx
- src/Pages/Travel/TravelTicekBook/BusFilter.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
Polish bus card on travel ticket page
> Polish bus card on travel ticket page

- src/Pages/Events/EventDetails/EventDetails.jsx
- src/Pages/Events/EventsComponents/CommentModal.jsx
- src/Pages/Events/EventsComponents/CountdownTimer.jsx
- src/Pages/Events/EventsComponents/SuggestedEventCard.jsx
> added add calender button

- src/Pages/Dashboard/Travel/MyBusServices/MyBusServices.jsx
- src/Pages/Page404/Page404.jsx
- src/Routes/Route.jsx
- src/Shared/Footer/Footer.jsx
404Page and footer page design done
> 404Page and footer page design done

- package-lock.json
- package.json
- src/Pages/Travel/TravelPaymentReceipt/TravelPaymentSuccess.jsx
- src/Routes/Route.jsx
fixed bugs and more data in travel payment success page
> fixed bugs and more data in travel payment success page

- src/Hooks/useCurrentUser.jsx
- src/Pages/Travel/TravelTicekBook/TravelSelectSet.jsx
- src/Provider/TravelProvider.jsx
added current user hook and added dynamic data on travel set select page
> added current user hook and added dynamic data on travel set select page

- package-lock.json
- package.json
- src/Pages/Dashboard/Travel/AddBusCompany/AddBusCompany.jsx
- src/Pages/Dashboard/Travel/AddBusCompany/BusDetailsForm.jsx
- src/Pages/Travel/AddTravelService/AddTravelService.jsx
- src/Routes/Route.jsx
added Add Your bus details in dashboard
> added Add Your bus details in dashboard

- package-lock.json
- package.json
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
- src/app/store.js
- src/features/allBus/allBusSlice.js
- src/main.jsx
implement redux , create store, allbusSlice and replace data using redux on travel ticket page
> implement redux , create store, allbusSlice and replace data using redux on travel ticket page

- src/Pages/Dashboard/Travel/MyBusServices/MyBusServices.jsx
- src/Pages/Dashboard/Travel/SoldTickets/SoldTickets.jsx
- src/Pages/Dashboard/Travel/SoldTickets/useSoldTicket.jsx
> fixed sold ticket page

- src/Pages/Travel/TravelTicekBook/BusUnavailable.jsx
- src/Pages/Travel/TravelTicekBook/TravelBusTicketPage.jsx
> added unavailable use section

- src/Shared/Footer/Footer.jsx
fixed some issue in footer design
> fixed some issue in footer design

- src/Layout/dashboard.jsx
- src/Pages/Dashboard/User/TicketBought/TicketBought.jsx
- src/Routes/Route.jsx
Hello , I added ticket bought 50% done
> adding ticket bought 50% done

- src/Pages/Dashboard/User/TicketBought/TicketBought.jsx
hello, I fixed user ticker bought dashboard
> fixed user ticker bought dashboard

- src/Pages/Dashboard/Profile/ProfileComponents/UserProfile.jsx
> fixed user profile
